
-- --create user
-- CREATE USER @POSTGRES_USER WITH LOGIN PASSWORD '@POSTGRES_PASSWORD';
-- -- --or update its password
-- -- ALTER USER $POSTGRES_USER WITH PASSWORD '$POSTGRES_PASSWORD';

-- -- --change password validity period
-- -- ALTER USER <USER> VALID UNTIL 'infinity';

-- --create database
-- CREATE DATABASE @POSTGRES_DATABASE OWNER @POSTGRES_USER; 
-- --ENCODING 'UTF8' LC_COLLATE='fr_FR.UTF8' LC_CTYPE='fr_FR.UTF8' TEMPLATE template0;
-- GRANT ALL PRIVILEGES ON DATABASE @POSTGRES_DATABASE TO @POSTGRES_USER;

